# Generated by Django 2.2.7 on 2019-11-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_choices_params', models.CharField(choices=[('checking', 'CHECKING'), ('savings', 'SAVINGS'), ('none', 'NONE')], default=('checking', 'CHECKING'), max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('location_city', models.CharField(max_length=50)),
                ('location_id', models.CharField(max_length=25)),
            ],
        ),
    ]
